"""
ai_synthesis.py — Full AI-powered trading desk roundtable via Gemini.

All 5 personas are generated by a single Gemini call. Personas are produced
in sequence so later speakers can (and must) challenge earlier ones — creating
a genuine debate rather than five parallel summaries.

Falls back to the full rule-based roundtable transparently on any failure.

API key priority:
  1. GEMINI_API_KEY environment variable
  2. GEMINI_API_KEY in config.py

Get a free key (1 500 req/day) at https://aistudio.google.com
"""

from __future__ import annotations

import json
import logging
import os
import time
from typing import Optional

logger = logging.getLogger(__name__)

_MODEL_NAME = "models/gemini-2.5-flash-lite"

# ── System prompt ──────────────────────────────────────────────────────────
_SYSTEM_PROMPT = """\
You are running a live trading desk roundtable with 5 distinct voices debating \
whether to trade today. You will be given quantitative market data and must generate \
all 5 personas IN ORDER. Because you generate them sequentially, each persona \
from #2 onward is aware of what the previous speakers said — use that to create \
genuine disagreement, not parallel summaries.

RULES FOR SHARP DEBATE (strictly enforced):
1. NO DATA SUMMARIES. You are not a data reporter. Wrong: "VIX is 17, which is elevated." \
Right: "VIX 17 with a confirmed bull stack is the sweet spot — you get trend without paying \
for panic. The Risk Manager calling this cautious is dead wrong." Give opinions, not readings.
2. FIND NON-OBVIOUS COMBINATIONS. What does this specific mix of signals mean that \
no single indicator shows? E.g. "Full bull stack + narrow breadth + VIX falling = \
this rally is real but thin. The exits will be crowded."
3. PERSONAS 2, 3, 4 MUST CHALLENGE. Use the prior speaker's name. Say what they got \
wrong or missed. If you agree, say WHY they're right and add a sharper angle.
4. DESK HEAD ADJUDICATES. Name who won the debate and why. Give ONE clear directive — \
traders need to know exactly what to do. No hedging.
5. EVERY POINT must be a specific, actionable trade insight — not a description.

PERSONAS AND THEIR DOMAINS:
- The Technician: price structure, MAs, RSI, MACD, tape character. Cares about entries.
- The Macro Strategist: yields, dollar, liquidity, Fed, BTC as risk proxy. Cares about the regime.
- The Risk Manager: VIX term structure, SKEW, flow sentiment, breadth divergence. Cares about tail risk and sizing.
- The Sector Rotator: RS rankings, sector leadership, IWM vs SPY, where money is actually flowing. Cares about what to buy.
- The Desk Head: adjudicates the debate. Takes a side. Gives the execution directive.

Respond with ONLY valid JSON (no markdown fences) matching this exact schema:
{
  "personas": [
    {
      "persona": "The Technician",
      "role": "Price Structure · MAs · RSI · MACD · Tape",
      "avatar": "📊",
      "stance": "<Bullish|Cautious|Defensive|Bearish>",
      "stance_color": "<green|yellow|orange|red>",
      "read": "string — 2-3 sharp sentences. Opinion-first. No hedging.",
      "points": [
        {"icon": "<✅|⚠️|🔴|🎯|⚡>", "text": "string — specific, actionable insight"}
      ],
      "verdict": "string — one decisive sentence, max 15 words"
    },
    {
      "persona": "The Macro Strategist",
      "role": "Yields · Dollar · Liquidity · Fed · BTC",
      "avatar": "🌐",
      "stance": "...",
      "stance_color": "...",
      "read": "string — MUST reference The Technician by name. Challenge or qualify their take with macro context.",
      "points": [...],
      "verdict": "..."
    },
    {
      "persona": "The Risk Manager",
      "role": "VIX · SKEW · Flow · Breadth · Sizing",
      "avatar": "🛡",
      "stance": "...",
      "stance_color": "...",
      "read": "string — MUST reference at least one prior speaker by name. What risk angle did they miss?",
      "points": [...],
      "verdict": "..."
    },
    {
      "persona": "The Sector Rotator",
      "role": "RS Rankings · Sector Flow · Leaders · IWM",
      "avatar": "🔄",
      "stance": "...",
      "stance_color": "...",
      "read": "string — MUST reference at least one prior speaker. Where is money actually moving — and does it confirm or contradict the debate so far?",
      "points": [...],
      "verdict": "..."
    },
    {
      "persona": "The Desk Head",
      "role": "Adjudicator · Final Call · Execution",
      "avatar": "🎯",
      "stance": "...",
      "stance_color": "...",
      "read": "string — Name who won the debate and why. Take a hard position. No 'on one hand'.",
      "points": [
        {"icon": "🎯", "text": "VERDICT: <decision> · Score <score>/100 · <position_size>"},
        {"icon": "...", "text": "..."},
        {"icon": "...", "text": "..."},
        {"icon": "⚡", "text": "EXECUTION: one sentence on exact size and stops"}
      ],
      "verdict": "string — the single most important thing a trader needs to hear right now"
    }
  ]
}

Each persona must have exactly 3 points (Desk Head: exactly 4).
Stance/stance_color mapping: Bullish=green, Cautious=yellow, Defensive=orange, Bearish=red.
"""

# ── Lazy client init ───────────────────────────────────────────────────────
_client = None
_client_loaded = False


def _get_client():
    """Lazily initialise Gemini client. Returns client or None."""
    global _client, _client_loaded
    if _client_loaded:
        return _client

    _client_loaded = True
    try:
        from google import genai  # type: ignore[import]
    except ImportError:
        logger.info("google-genai not installed. Run: pip3 install google-genai")
        return None

    api_key = os.environ.get("GEMINI_API_KEY", "").strip()
    if not api_key:
        try:
            from config import GEMINI_API_KEY as cfg_key  # type: ignore[attr-defined]
            api_key = (cfg_key or "").strip()
        except (ImportError, AttributeError):
            pass

    if not api_key:
        logger.info("GEMINI_API_KEY not set — AI roundtable disabled, using rule-based fallback.")
        return None

    try:
        _client = genai.Client(api_key=api_key)
        logger.info("Gemini client initialised (%s) — AI roundtable active.", _MODEL_NAME)
        return _client
    except Exception as exc:
        logger.warning("Gemini init failed: %s", exc)
        return None


# ── Prompt builder ─────────────────────────────────────────────────────────

def _build_prompt(dashboard: dict) -> str:
    """Build a dense, information-rich market data snapshot for the AI."""
    total    = dashboard.get("total_score", 0)
    decision = dashboard.get("decision", "—")
    pos_size = dashboard.get("position_size", "—")
    conflicts = dashboard.get("conflicts", [])
    warnings  = [c for c in conflicts if c.get("severity") == "warning"]

    pillars  = dashboard.get("pillars", {})
    macro_d  = pillars.get("macro",      {}).get("details", {})
    vol_d    = pillars.get("volatility", {}).get("details", {})
    trend_d  = pillars.get("trend",      {}).get("details", {})
    breadth_d= pillars.get("breadth",    {}).get("details", {})
    mom_d    = pillars.get("momentum",   {}).get("details", {})

    # Pillar scores
    pillar_scores = {
        name: data.get("score", "?")
        for name, data in pillars.items()
    }

    # Sector RS leaders/laggards
    sector_rs = mom_d.get("sector_rs", []) or []
    rs_top3   = [f"{s['name']} RS{s['rs_score']:+.1f}" for s in sector_rs[:3]  if s.get("rs_score") is not None]
    rs_bot3   = [f"{s['name']} RS{s['rs_score']:+.1f}" for s in sector_rs[-3:] if s.get("rs_score") is not None]

    data = {
        # ── Composite ─────────────────────────────────────────────────────
        "composite_score": total,
        "decision":        decision,
        "position_size":   pos_size,
        "pillar_scores":   pillar_scores,

        # ── Trend / Tape ──────────────────────────────────────────────────
        "spy_regime":      trend_d.get("regime"),
        "above_20d":       trend_d.get("above_20"),
        "above_50d":       trend_d.get("above_50"),
        "above_200d":      trend_d.get("above_200"),
        "tape_character":  trend_d.get("char_label"),
        "ath_dist_pct":    trend_d.get("ath_dist"),
        "rsi14":           trend_d.get("rsi14"),
        "macd_label":      trend_d.get("macd_label"),
        "spy_change_pct":  trend_d.get("spy_change_pct"),

        # ── Volatility ────────────────────────────────────────────────────
        "vix":             vol_d.get("vix_level"),
        "vix_label":       vol_d.get("vix_label"),
        "vix_trend":       vol_d.get("vix_trend"),
        "vix_pctile":      vol_d.get("vix_pctile"),
        "vix9d_label":     vol_d.get("vix9d_label"),
        "skew_label":      vol_d.get("skew_label"),
        "flow_label":      vol_d.get("flow_label"),
        "flow_score":      vol_d.get("flow_score"),

        # ── Macro ─────────────────────────────────────────────────────────
        "tnx_yield":       macro_d.get("tnx_value"),
        "yield_direction": macro_d.get("yield_direction"),
        "yield_label":     macro_d.get("yield_label"),
        "dxy_label":       macro_d.get("dxy_label"),
        "dxy_change_pct":  macro_d.get("dxy_change_pct"),
        "btc_trend":       macro_d.get("btc_trend"),
        "btc_from_high":   macro_d.get("btc_from_high"),
        "fomc_days":       macro_d.get("fomc_days"),
        "fomc_date":       macro_d.get("fomc_date"),

        # ── Breadth ───────────────────────────────────────────────────────
        "sectors_positive":   breadth_d.get("sectors_positive"),
        "sectors_total":      breadth_d.get("sectors_total"),
        "rsp_vs_spy_pct":     breadth_d.get("rsp_vs_spy"),
        "iwm_vs_spy_pct":     mom_d.get("iwm_vs_spy"),
        "participation":      mom_d.get("participation"),

        # ── Rotation ──────────────────────────────────────────────────────
        "rs_leaders":  rs_top3,
        "rs_laggards": rs_bot3,

        # ── Active conflicts ──────────────────────────────────────────────
        "active_conflicts": [
            {"title": c["title"], "detail": c.get("detail", "")[:100]}
            for c in warnings
        ],
    }

    return (
        "LIVE MARKET DATA (use specific numbers in your debate):\n"
        + json.dumps(data, indent=2)
        + "\n\nGenerate the full roundtable debate JSON now."
    )


# ── Validation helpers ─────────────────────────────────────────────────────

_VALID_STANCES = {"Bullish", "Cautious", "Defensive", "Bearish"}
_VALID_COLORS  = {"green", "yellow", "orange", "red"}
_PERSONA_NAMES = [
    "The Technician", "The Macro Strategist",
    "The Risk Manager", "The Sector Rotator", "The Desk Head",
]


def _validate_and_stamp(personas: list, latency_ms: int) -> list | None:
    """Validate the parsed persona list and add ai_powered metadata."""
    if not isinstance(personas, list) or len(personas) != 5:
        logger.warning("AI returned %d personas (expected 5)", len(personas) if isinstance(personas, list) else -1)
        return None

    result = []
    for i, p in enumerate(personas):
        if not isinstance(p, dict):
            return None
        required = ("persona", "role", "avatar", "stance", "stance_color", "read", "points", "verdict")
        if not all(k in p for k in required):
            logger.warning("Persona %d missing keys: %s", i, [k for k in required if k not in p])
            return None
        if p.get("stance") not in _VALID_STANCES or p.get("stance_color") not in _VALID_COLORS:
            # Auto-correct stance/color from composite score for desk head
            pass  # leave as-is, UI will handle unknown values gracefully

        result.append({**p, "ai_powered": True, "latency_ms": latency_ms})

    return result


# ── Public entry point ─────────────────────────────────────────────────────

def ai_roundtable(dashboard: dict) -> dict | None:
    """
    Generate a full AI-powered roundtable debate (all 5 personas) via Gemini.

    Returns a dict with key 'personas' (list of 5) and 'timestamp',
    matching the shape expected by analysis.roundtable().

    Returns None on any failure — caller falls back to rule-based roundtable.
    """
    client = _get_client()
    if client is None:
        return None

    try:
        from google import genai  # type: ignore[import]
        from google.genai import types  # type: ignore[import]

        prompt = _build_prompt(dashboard)
        t0 = time.time()

        response = client.models.generate_content(
            model=_MODEL_NAME,
            contents=prompt,
            config=types.GenerateContentConfig(
                system_instruction=_SYSTEM_PROMPT,
                temperature=0.7,        # higher = sharper opinions, less repetition
                max_output_tokens=2048,
                response_mime_type="application/json",
            ),
        )
        elapsed = time.time() - t0
        latency_ms = round(elapsed * 1000)

        raw = (response.text or "").strip()

        # Strip markdown fences if the model ignores response_mime_type
        if raw.startswith("```"):
            parts = raw.split("```")
            raw = parts[1] if len(parts) >= 3 else parts[-1]
            raw = raw.lstrip("json").strip()

        parsed = json.loads(raw)

        # Support both {"personas": [...]} and bare [...]
        if isinstance(parsed, dict) and "personas" in parsed:
            raw_personas = parsed["personas"]
        elif isinstance(parsed, list):
            raw_personas = parsed
        else:
            logger.warning("Unexpected AI response shape: %s", type(parsed))
            return None

        personas = _validate_and_stamp(raw_personas, latency_ms)
        if personas is None:
            return None

        logger.info(
            "AI roundtable completed in %.2fs (%d personas, model=%s)",
            elapsed, len(personas), _MODEL_NAME,
        )

        return {
            "personas":  personas,
            "timestamp": time.strftime("%H:%M UTC", time.gmtime()),
        }

    except json.JSONDecodeError as exc:
        logger.warning("Gemini returned invalid JSON: %s", exc)
        return None
    except Exception as exc:
        logger.warning("AI roundtable failed (%s): %s", type(exc).__name__, exc)
        return None


